### ISSUE TITLE
`setState` console warnings

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/victory-animation#18]
Oh hai!

I'm seeing "Don't call `setState`" console warnings bubble up from `victory-animation` in rerender-intensive situations: navigating between routes, resizing voronoi layouts, etc. They're all coming from `functionToBeCalledEachFrame`:

![screen shot 2015-10-22 at 6 16 48 pm](https://cloud.githubusercontent.com/assets/6352327/10682320/358f9f48-78e9-11e5-9946-6f55378b50b4.png)

It looks like the `victory-animation` components are unmounting *between* async RAF callbacks, which in turn try to set state. If so, something like
```
componentWillUnmount() {
  if (this.raf) {
    cancelAnimationFrame(this.raf);
  }
}
```
should do the trick, right? In my (cursory) testing, this has cleared up *all* routing-based warnings and *most* resizing-voronoi-based errors; that said, not PRing yet because I'm curious what the experts think. :)

/cc @exogen @boygirl

**Comment by exogen** [comment]
Sounds about right, but what's the full warning? "Don't call setState ...[I'm assuming more explanation here]..."

**Comment by kenwheeler** [comment]
@david-davidson yeah that should do it

**Comment by david-davidson** [comment]
@exogen Sorry for vagueness. :) The full warning is `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.`:
![screen shot 2015-10-23 at 9 26 25 am](https://cloud.githubusercontent.com/assets/6352327/10698935/4bfae20e-7968-11e5-838a-05afea96bdb3.png)

I'll put in a PR!
