### ISSUE TITLE
Bump version number?

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/victory-animation#20]
Now that #19 is in, mind if I bump the version number and publish?

More broadly, I'm using `victory-animation` by way of `victory-line` and `victory-voronoi`, and it would be awesome to get the new `console.warn`-free behavior there--any objections to updating those packages to the latest `victory-animation`, too?

I know you folks have a lot of moving parts right now, so just wanted to check first. :)
/cc @exogen @boygirl

**Comment by boygirl** [comment]
@david-davidson bumped and published. I'll update the dependency on victory-line and republish too. I don't have publish access on voronoi yet. I'll pester Colin for it.

**Comment by david-davidson** [comment]
@boygirl Thanks so much! :ok_hand:
