### ISSUE TITLE
Migrate to duration for animation speed

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/victory-animation#21]
Right now we use `velocity`, which isn't really a sane way to animate: the amount of time an animation takes ends up depending on the user's CPU speed, and there's no way to sync up animations with each other or with other events, since the timing of the animation can't be determined.

**Comment by qpre** [comment]
anyway one could help with this ?

I really do enjoy using VictoryLine but when it comes to a live-updated component using `velocity` makes it difficult to chain animations smoothly, where one could rely on a `duration` to do so.

**Comment by divmain** [comment]
Close by https://github.com/FormidableLabs/victory-core/pull/9.
