### ISSUE TITLE
Timeout interval not being cleared.

### ISSUE THREAD

**Issue by D-TUCKER** [FormidableLabs/victory-animation#25]
I am running into an issue similar to https://github.com/FormidableLabs/victory-animation/issues/18.  I think is because the timeout is not getting cleared when the component unmounts.  I think it should be possible to use clearTimeout it in componentWillUnmount.  

I just can't get the builder thing working for the life of me.  Maybe I'll try it on a mac when I get home.

**Comment by boygirl** [comment]
@D-TUCKER Thanks for bearing with us on the transition to builder. Things are in a little bit of an in-between phase right now. Look forward to an actual release candidate in the next couple weeks. @kenwheeler or I will look into the clearTimeout suggestion in the meantime.

**Comment by coopy** [comment]
Closed via https://github.com/FormidableLabs/victory-animation/issues/18
