### ISSUE TITLE
Add enter and exit transitions

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory-animation#28]
Tween states are currently animating smoothly, but `enter` and `exit` events are jerky.
See https://github.com/FormidableLabs/victory-pie/issues/19 for an example.

**Comment by coopy** [comment]
@kenwheeler How's this going?

**Comment by kenwheeler** [comment]
@coopy needs work, trying to base it loosely around the way it works here https://github.com/chenglou/react-motion#transitionmotion-

**Comment by coopy** [comment]
@kenwheeler can you write up a summary for where you are at on this? Maybe @exogen can pick this up when he's got a spare moment.

**Comment by kenwheeler** [comment]
Didn't get super far other than trying to figure out what an API would look like.

**Comment by coopy** [comment]
Do you have any API recommendations?

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-core#14
