### ISSUE TITLE
Retain format of numbers in interpolated strings

### ISSUE THREAD

**Issue by thochi** [FormidableLabs/victory-animation#45]
See https://github.com/FormidableLabs/victory/issues/200

**Comment by boygirl** [comment]
@thochi I'm sorry I dropped the ball on this one. We Just finished deprecating this repo, and including victory-animation code in [victory-core](https://github.com/FormidableLabs/victory-core). Could I ask you to move this PR?

**Comment by thochi** [comment]
hi @boygirl, yes i will move the final PR.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-core#12
